# Generated by Django 3.0.8 on 2020-11-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=50)),
                ('tipo_entidad', models.CharField(choices=[('EL', 'Electrica'), ('GS', 'Gas')], default='EL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_provincia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_tarifa', models.DateField()),
                ('fecha_fin_tarifa', models.DateField(blank=True, null=True)),
                ('precio_unitario', models.FloatField(max_length=8)),
                ('codigo', models.CharField(max_length=50)),
                ('consumo_minimo', models.IntegerField(max_length=5)),
                ('consumo_maximo', models.IntegerField(max_length=6)),
                ('cargo_fijo', models.FloatField(max_length=8)),
                ('tipo_tarifa', models.CharField(max_length=50)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_entidades.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_partido', models.CharField(max_length=20)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_entidades.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_localidad', models.CharField(max_length=20)),
                ('zona_bioambiental', models.CharField(max_length=20)),
                ('entidad', models.ManyToManyField(related_name='entidad', to='api_entidades.Entidad')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_entidades.Partido')),
            ],
        ),
    ]
