# Generated by Django 3.0.8 on 2020-11-06 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_entidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
