# Generated by Django 3.0.8 on 2021-10-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_entidades', '0003_auto_20211008_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='consumo_maximo',
            field=models.IntegerField(null=True),
        ),
    ]
