# Generated by Django 3.0.8 on 2021-09-04 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='estiqueta',
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E'), (5, 'F'), (6, 'G')], default=0)),
                ('fecha_desde', models.DateField(default=django.utils.timezone.now)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('borrado', models.BooleanField(default=False)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_inmuebles.Inmueble')),
            ],
        ),
    ]
