# Generated by Django 3.0.8 on 2021-10-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_inmuebles', '0002_auto_20211008_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerramiento',
            name='cerramientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_inmuebles.Cerramiento'),
        ),
    ]
