# Generated by Django 3.0.8 on 2021-10-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inmuebles', '0003_cerramiento_cerramientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerramiento',
            name='ambiente',
            field=models.ManyToManyField(related_name='cerramiento', to='api_inmuebles.Ambiente'),
        ),
        migrations.RemoveField(
            model_name='cerramiento',
            name='cerramientos',
        ),
        migrations.AddField(
            model_name='cerramiento',
            name='cerramientos',
            field=models.ManyToManyField(related_name='_cerramiento_cerramientos_+', to='api_inmuebles.Cerramiento'),
        ),
    ]
