# Generated by Django 3.0.8 on 2021-10-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inmuebles', '0004_auto_20211024_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerramiento',
            name='ambiente',
            field=models.ManyToManyField(blank=True, null=True, related_name='cerramiento', to='api_inmuebles.Ambiente'),
        ),
        migrations.AlterField(
            model_name='cerramiento',
            name='cerramientos',
            field=models.ManyToManyField(blank=True, null=True, related_name='_cerramiento_cerramientos_+', to='api_inmuebles.Cerramiento'),
        ),
    ]
