# Generated by Django 3.0.8 on 2021-11-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inmuebles', '0005_auto_20211024_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerramiento',
            name='superficie',
        ),
        migrations.AddField(
            model_name='cerramiento',
            name='alto',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='cerramiento',
            name='ancho',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
