# Generated by Django 3.0.8 on 2022-02-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_inmuebles', '0006_auto_20211112_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='nombre',
            new_name='direccion',
        ),
    ]
