# Generated by Django 3.0.8 on 2022-02-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inmuebles', '0007_auto_20220210_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='es_eficiente',
            field=models.BooleanField(default=True),
        ),
    ]
