# Generated by Django 3.0.8 on 2022-02-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_inmuebles', '0008_material_es_eficiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='clasificacion',
        ),
    ]
