# Generated by Django 3.0.8 on 2020-11-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artefacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artefacto', models.CharField(max_length=50)),
                ('consumo', models.IntegerField(default=0)),
                ('eficiencia', models.CharField(max_length=4)),
                ('categoria', models.CharField(default='Aires', max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('marca', models.CharField(default='S/N', max_length=20)),
                ('modelo', models.CharField(default='S/N', max_length=20)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
