# Generated by Django 3.0.8 on 2021-09-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_artefactos', '0002_artefacto_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefacto',
            name='etiqueta',
            field=models.IntegerField(choices=[(0, 'A+++'), (1, 'A++'), (2, 'A+'), (3, 'A'), (4, 'B'), (5, 'C'), (6, 'D'), (7, 'E'), (8, 'F'), (9, 'G')], default=0),
        ),
    ]
