# Generated by Django 3.0.8 on 2021-09-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_artefactos', '0003_auto_20210905_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefacto',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
