# Generated by Django 3.0.8 on 2021-10-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_artefactos', '0004_auto_20210907_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefacto',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'Aires'), (1, 'heladeras'), (2, 'Electronica'), (3, 'Iluminación'), (5, 'Lavarropas'), (4, 'Cocina'), (6, 'Calefacción'), (7, 'Baño')], default=0),
        ),
    ]
