# Generated by Django 3.0.8 on 2021-10-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_artefactos', '0006_auto_20211008_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefacto',
            name='etiqueta',
            field=models.CharField(choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A+++', max_length=4),
        ),
    ]
