# Generated by Django 3.0.8 on 2022-02-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_artefactos', '0009_artefactos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefactos',
            old_name='marca',
            new_name='marca_modelo',
        ),
        migrations.RemoveField(
            model_name='artefactos',
            name='modelo',
        ),
    ]
