# Generated by Django 3.0.8 on 2022-02-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_artefactos', '0011_artefacto2_marca_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefactos',
            name='marca_modelo',
        ),
        migrations.AddField(
            model_name='artefactos',
            name='marca',
            field=models.CharField(choices=[('BGH', 'BGH'), ('DREAN', 'DREAN')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artefactos',
            name='modelo',
            field=models.CharField(choices=[('bb55', 'bb55'), ('bb56', 'bb56'), ('fuzy22', 'Fuzy22'), ('blue9.0', 'blue9.0')], max_length=50, null=True),
        ),
    ]
